### ISSUE TITLE
[Roadmap] Project Anni in 2022

### ISSUE THREAD

**Issue by Yesterday17** [ProjectAnni/book#40]
## 参与者
@ProjectAnni/dev @ProjectAnni/metadata 

## Milestones

- 1.0.0-alpha: 确定 1.0 版本使用的各项协议，完成所有 P0/P1 需求 **<-- [Ongoing]**
- 1.0.0-beta: 完成列出的其他所有需求
- 1.0.0-rc: 正式版发布之前经历一段时间的使用，修复 Bug
- 1.0.0: 2022 年年内发布 1.0.0 正式版

## 符号

|符号|说明|
|----|----|
|`*` | Enhancement |
|`+` | Feature |
|`-` | Remove |
|`!` | Fix |
|`=` | Refactor |

### 模板

```markdown
- [ ] **`[P3][=]`** 描述文本
```
待补充。

**Comment by tuzi3040** [comment]
Roadmap（x
Milestone（〇
Project（〇

**Comment by Yesterday17** [comment]
## Anni

### 涉及项目

- [anni](https://github.com/ProjectAnni/anni/tree/master/anni)
- [anni-flac](https://github.com/ProjectAnni/anni/tree/master/anni-flac)
- [anni-common](https://github.com/ProjectAnni/anni/tree/master/anni-common)
- ~~[anni-derive](https://github.com/ProjectAnni/anni/tree/master/anni-derive)~~
- [anni-repo](https://github.com/ProjectAnni/anni/tree/master/anni-repo)
- [anni-clap-handler](https://github.com/ProjectAnni/anni/tree/master/anni-clap-handler)
- [anni-clap-handler-derive](https://github.com/ProjectAnni/anni/tree/master/anni-clap-handler-derive)

### TODO

- [x] **`[P0][=]`** 重新设计并文档化 `anni-clap-handler`
- [x] **`[P1][-]`** 移除 `anni-derive`
- [x] **`[P2][=]`** 移动 `anni flac check` 的功能至 `anni convention` 下
- [ ] **`[P2][=]`** `anni convention` 新增对封面存在性的检查
- [x] **`[P3][*]`** 增加 `anni split` 下对编码/解码器的检查，输出更友好的错误提示。
  - [ ] 如新增 `anni split --check .`，对该目录下音频格式的编码/解码器存在情况进行检查
- [ ] **`[P3][+]`** 增加 `ffmpeg` 供 `anni split` 使用
- [ ] **`[P3][!]`** 优化错误处理方式，整合 `log` 与 `exit code` 的关系（可能需要对 log 进行单独封装）
- [x] **`[P3][+]`** `anni repo` 增加 `clone` 子命令
- [ ] **`[P3][+]`** `anni repo` 增加 `diff` 子命令，对两次提交之间发生修改的内容进行处理
- [ ] **`[P3][+]`** 删除所有旧兼容性代码，或移动至 `anni legacy` 子命令下并择期移除
- [x] **`[P3][+]`** `anni split` 增加 `--dry-run` 以输出调试文本

**Comment by Yesterday17** [comment]
## Annil

### 涉及项目

- [annil](https://github.com/ProjectAnni/anni/tree/master/annil)
- [anni-backend](https://github.com/ProjectAnni/anni/tree/master/anni-backend)

### TODO

- [x] **`[P2][=]`** 将 `anni-backend` 重命名为 `anni-provider` 以避免歧义 [88f4c76](https://github.com/ProjectAnni/anni/commit/88f4c766f2f856f31afa14d42915436b38845ba4) [a02f4ec](https://github.com/ProjectAnni/anni/commit/a02f4ec0672183edeab27e8b77582a5975f773b7)
- [x] **`[P3][+]`** Range 支持 #48 
- [x] **`[P2][+]`** 重新定义严格目录格式
- [x] **`[P3][+]`** 支持严格目录格式
- [x] **`[P3][*]`** 将更多硬编码内容抽出到配置文件
- [ ] ~~**`[P3][+]`** 使用 `clap` 解析命令参数~~
- [x] **`[P3][=]`** 一定程度上摆脱对预生成数据源的依赖，或规范化依赖方式
- [x] **`[P3][*]`** 加快 `drive` 的 `HEAD` 返回速度

**Comment by Yesterday17** [comment]
## Anniv

待填写 @SeraphJACK 

### 涉及项目

- [anniv-go](https://github.com/ProjectAnni/anniv-go)
- [anniv](https://github.com/ProjectAnni/anniv)（GraphQL 实验场）

### TODO

- [ ] **`[P3][+]`** 用户权限控制
- [ ] **`[P2][=]`** 爬取歌词并加入 `Anniv`

**Comment by Yesterday17** [comment]
## Anniw

待填写 @Last-Order 

### 涉及项目

- [anniw](https://github.com/ProjectAnni/anniw)

### TODO

- [x] **`[P0][+]`** 播放列表
- [x] **`[P1][+]`** 整合所有的音频仓库，根据优先级自动选择可用资源
- [x] **`[P1][+]`** 定时自动更新音频仓库的资源
- [ ] **`[P2][+]`** `Album Wall` 排序（如按发售日期、标题等）
- [ ] **`[P3][+]`** （选项支持）播放时将页面标题修改为 `曲名 | 站点名`
- [ ] **`[P3][+]`** 专辑列表增加一个 `radio button` 过滤无资源的专辑

**Comment by Yesterday17** [comment]
## Annix

### 涉及项目

- [annix](https://github.com/ProjectAnni/annix)

### Fork 项目

- [marquee](https://github.com/ProjectAnni/marquee)
- [libwinmedia](https://github.com/ProjectAnni/libwinmedia)
- [just_audio_libwinmedia](https://github.com/ProjectAnni/just_audio_libwinmedia)

### TODO

- [x] **`[P0][+]`** 播放页面
- [x] **`[P0][+]`** 登录 Anniv 时的错误提示
- [x] **`[P0][+]`** 喜欢歌曲，已喜欢列表
- [ ] **`[P0][+]`** 播放列表
- [x] **`[P0][+]`** 搜索
- [x] **`[P0][!]`** `macOS` 下播放列表要等到所有资源加载完成才会开始播放
- [x] **`[P1][+]`** 播放统计
- [x] **`[P1][+]`** 歌词
- [ ] **`[P2][+]`** `marquee` 支持文本对齐方向
- [ ] ~~**`[P3][=]`** 当 `libwinmedia` 发布新版本时，使用对应的最新版本而非 Fork~~ 已 Deprecate

**Comment by Yesterday17** [comment]
## 其他

### 涉及项目

- [radio](https://github.com/ProjectAnni/radio)
- [anni-artist](https://github.com/ProjectAnni/anni-artist)
- [anni-fetch](https://github.com/ProjectAnni/anni-fetch)
- [annisonic](https://github.com/ProjectAnni/annisonic)

### TODO

- [x] **`[P2][=]`** `radio` 支持最新的 `annil` 协议
- [ ] **`[P1][=]`** `anni-artist` 以 `wasm` 为 `target` 生成并打包发布至 `npm`
- [ ] **`[P3][=]`** `annisonic` 支持最新 `annil` 协议和 `anniv`
- [ ] **`[P4][=]`** 解析 MusicBrainz 导出数据库格式

**Comment by Yesterday17** [comment]
https://github.com/ProjectAnni/book/issues/80 确定后，本 issue 将会关闭
